---
- name: Test Playbook
  hosts: all
  become: yes
  vars:
    pw: "$6$mysecretsalt$8OKI83Ge0RDRKdHRVm4lNBp4manv7Dlw4sVke3B8a4nJNBf9BgPzu11c9a/MjXZwD5xkJ5JcePl2UhikFs9tP."
  tasks: 
    - name: Ctrate Group
      group:
        name: admins
        state: present

    - name: Create Users
      user:
        name: "{{ item }}"
        comment: "{{ item }}"
        generate_ssh_key: yes
        group: admins
        groups: wheel
        home: /home/{{ item }}
        create_home: yes
        password: "{{ pw }}"
        state: present
      with_items:
        - "scoffers"


