---
- name: Patch System
  hosts: all
  become: yes
  gather_facts: yes
  tasks:

    - name: RHEL/CentOS Block
      block:
        - name: Show Fact
          debug:
            msg: Upgrading {{ ansible_distribution }}

        - name: Perform Update of latest package
          yum:
            name: "*"
            state: latest
            update_latest: yes
          register: packages
          notify: Reboot Server
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Display unchanged message
      debug:
        msg:  "Server {{ ansible_hostname }} unhanged"
      when: not packages.changed

  handlers:
    - name: Import Handlers
      import_tasks: handlers/main.hml

