---
- name: Initial Playbook
  hosts: all
  become: yes
  vars:
    pw: "$6$mysecretsalt$8OKI83Ge0RDRKdHRVm4lNBp4manv7Dlw4sVke3B8a4nJNBf9BgPzu11c9a/MjXZwD5xkJ5JcePl2UhikFs9tP."
  vars_files:
    - vault/redsubs.yml
  tasks:
    - name: Set timezone
      timezone:
        name: Europe/London

    - name: Copy motd
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644

    - name: Cerate Group
      group:
        name: admins
        state: present

    - name: Create Users
      user:
        name: "{{ item }}"
        comment: "{{ item }}"
        generate_ssh_key: yes
        group: admins
        groups: wheel
        home: /home/{{ item }}
        create_home: yes
        password: "{{ pw }}"
        state: present
      with_items:
        - "scoffers"

    - name: Ensure Admins can SUDO without password
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%admins'
        line: '%admins ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'


    - name: Install software
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - "git"

    - name: Ensure sshd is started
      service:
        name: sshd
        enabled: true
        state: started

    - name: Copy cramfs modproble file if it is not present
      copy:
        src:  cramfs.conf
        dest: /etc/modprobe.d/cramfs.conf
        owner: root
        group: root
        mode: 0644
        force: no
      notify: copy_cramfs
      when:  ansible_distribution_major_version ==  "8"

    - name: Loop over ansible mounts
      debug:
        msg: Mount is {{ item }}
      loop:
        - "{{ ansible_mounts }}"

    - name: RHEL Block
      block:
        - name: Include RGEL Tasks
          include_tasks: rhel.yml
      when:  ansible_distribution  == 'RedHat'

  handlers:
    - name: copy_cramfs
      command:
       cmd: "/usr/sbin/rmmod cramfs"
